#!/bin/bash
#  Script to generate the problem dependent files used
#     in the nozzle case for Miranda
#  Script will: 
#           1)  Ensure gridgen exists in local folder,
#                  if not it is downloaded and built.
#           2)  Compile and run the papam_nozzle.f90 routines 
#                  for use in the grid generation and initialization.
#           3)  Generate the Grid using gridgen
#           4)  Make the 2d initialization file, grid file and 
#                  parameters file.
#           5)  Tar up the dependent files for use in nozzle case




#  Check to see if gridgen-c exists
ggEXEC="gridgen/gridgen"
ggCONF="gridgen/configure"
one=1

# bash check if directory exists
if [ -e $ggEXEC ]; then
    echo "gridgen-c exists... check complete"
    download=0
    build=0 
else 
    if [ -e $ggCONF ]; then
	build=1
	download=0
    else
	build=1
	download=1
    fi
fi

#  Download the files
if [ $download -eq $one ]; then
    echo "Downloading gridgen-c from repository"
    svn checkout http://gridgen-c.googlecode.com/svn
    mv svn/gridgen .
    rm -rf svn
fi

#  Build the executable
if [ $build -eq $one ]; then
    echo "Building gridgen-c from source"
    cd gridgen
    ./configure
    make
    cd ..
    echo "Build Successful"
fi

#  Compile and run the f90 routines
ifort $1 -o rr_noz
./rr_noz 0

#  Using the boundary data from above, make the mesh
$ggEXEC -v noz.prm

#  Re-run the f90 routine and make the initialization file
./rr_noz 1

#  Tar-up and problem dependent files and label
#  also include the papam_nozzle.f90 file that was used to generate the current mesh
TARFILE=rrdep_$(date +%Y.%m.%d_%H.%M.%S).tgz
mkdir rr_dep
cp nozzle.grid nozzle_init.tec nozzle.inflow $1 rr_dep
mv rr_dep/nozzle_init.tec rr_dep/nozzle.init
tar cvzf $TARFILE rr_dep
rm -rf rr_dep

#  All done... clean up and echo result
echo "Initialization complete"

